export const ADD_NUMBER = 'ADD_NUMBER';
export const LANG = 'LANG';
export const HOME_BLOCKDETAILS = 'HOME_BLOCKDETAILS';
export const SEARCH_BLOCKHEIGHT = 'SEARCH_BLOCKHEIGHT';
export const SEARCH_TRANSACTION = 'SEARCH_TRANSACTION';